#!/usr/bin/env python3
"""Read/write helper for ~/.config/machine-setup/machine.toml.

The machine config is the only thing the bootstrap persists between runs. It
holds:
    identities          = ["personal", "work"]      # which BW identities to install
    extra_components    = ["claude-code", ...]      # optional components on top of required
    identity_overrides  = {<name>: {<host>: {<field>: value}}}
    component_config    = {<component>: {<field>: value}}

This module emits / consumes the entire file as JSON so bash and PowerShell
can manipulate it without parsing TOML themselves.

Usage:
    python3 lib/machine_config.py load <path>          -> JSON to stdout
    python3 lib/machine_config.py dump <path>          <- JSON on stdin (writes file)
    python3 lib/machine_config.py default              -> JSON of empty machine config
"""
from __future__ import annotations
import argparse, json, os, sys
from pathlib import Path

try:
    import tomllib
except ImportError:
    import tomli as tomllib  # type: ignore


SCHEMA_KEYS = ("identities", "extra_components", "identity_overrides", "component_config")
KEY_RE = __import__("re").compile(r'^[A-Za-z_][A-Za-z0-9_-]*$')


def _empty() -> dict:
    return {
        "identities": [],
        "extra_components": [],
        "identity_overrides": {},
        "component_config": {},
    }


def cmd_default(_):
    print(json.dumps(_empty()))


def cmd_load(args):
    p = Path(args.path)
    if not p.exists():
        print(json.dumps(_empty()))
        return
    try:
        data = tomllib.loads(p.read_text())
    except Exception as e:
        print(f"  WARN: machine.toml parse error: {e}", file=sys.stderr)
        print(json.dumps(_empty()))
        return
    out = _empty()
    # Carry over only known fields. Unknown keys (e.g. legacy `profile = ...`,
    # `components = [...]`) are returned in a `_legacy` block so callers can
    # decide whether to migrate.
    legacy = {}
    for k, v in data.items():
        if k in SCHEMA_KEYS:
            out[k] = v
        else:
            legacy[k] = v
    if legacy:
        out["_legacy"] = legacy
    print(json.dumps(out))


def cmd_dump(args):
    payload = json.load(sys.stdin)
    p = Path(args.path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(_emit_toml(payload))


# ─────────────────────────────────────────────────────────────────────────────

def _quote_string(s: str) -> str:
    if "\n" in s or "\\" in s or "\"" in s:
        # Use a basic-string with escapes
        s = s.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n")
    return f'"{s}"'


def _quote_key(s: str) -> str:
    """Bare key if it matches [A-Za-z_][A-Za-z0-9_-]*, else quoted."""
    if KEY_RE.match(s):
        return s
    return _quote_string(s)


def _format_value(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, str):
        return _quote_string(v)
    if isinstance(v, list):
        items = ", ".join(_format_value(x) for x in v)
        return f"[{items}]"
    raise TypeError(f"cannot serialize {type(v)} to TOML inline value")


def _emit_table(name_path: list[str], table: dict, lines: list[str]) -> None:
    """Recursively emit a TOML table. name_path is the dotted prefix
    (already key-quoted as needed)."""
    scalars, subtables = [], []
    for k, v in table.items():
        if isinstance(v, dict):
            subtables.append((k, v))
        else:
            scalars.append((k, v))

    if name_path:
        lines.append(f"[{'.'.join(name_path)}]")
    for k, v in scalars:
        lines.append(f"{_quote_key(k)} = {_format_value(v)}")
    if scalars and subtables:
        lines.append("")

    for k, v in subtables:
        sub_path = name_path + [_quote_key(k)]
        _emit_table(sub_path, v, lines)
        lines.append("")


def _emit_toml(payload: dict) -> str:
    """Emit a TOML file from the payload dict.
    Order: identities, extra_components, then nested tables (identity_overrides,
    component_config). Anything else passed in is appended at the end.
    """
    lines = [
        "# Auto-generated by machine-setup. Edit any field to override on next run,",
        "# or delete the file to be re-prompted.",
        "",
    ]

    flat = {}
    nested = {}
    extras = {}
    for k, v in payload.items():
        if k.startswith("_"):
            continue
        if k in ("identities", "extra_components"):
            flat[k] = v
        elif k in ("identity_overrides", "component_config"):
            nested[k] = v
        else:
            # unknown — keep at end so we don't silently drop user-added fields
            extras[k] = v

    # Flat scalars / lists first
    for k in ("identities", "extra_components"):
        if k in flat:
            lines.append(f"{k} = {_format_value(flat[k])}")
    if flat:
        lines.append("")

    # Nested tables
    for top in ("identity_overrides", "component_config"):
        block = nested.get(top) or {}
        if not block:
            continue
        for sub_name, sub_table in block.items():
            if not isinstance(sub_table, dict):
                continue
            _emit_table([top, _quote_key(sub_name)], sub_table, lines)

    for k, v in extras.items():
        if isinstance(v, dict):
            _emit_table([_quote_key(k)], v, lines)
        else:
            lines.append(f"{_quote_key(k)} = {_format_value(v)}")

    # Compact runs of blank lines
    out = "\n".join(lines)
    while "\n\n\n" in out:
        out = out.replace("\n\n\n", "\n\n")
    if not out.endswith("\n"):
        out += "\n"
    return out


def main():
    p = argparse.ArgumentParser()
    sub = p.add_subparsers(dest="cmd", required=True)
    p_default = sub.add_parser("default", help="emit empty config JSON")
    p_default.set_defaults(func=cmd_default)
    p_load = sub.add_parser("load", help="read machine.toml -> JSON on stdout")
    p_load.add_argument("path")
    p_load.set_defaults(func=cmd_load)
    p_dump = sub.add_parser("dump", help="write machine.toml from JSON on stdin")
    p_dump.add_argument("path")
    p_dump.set_defaults(func=cmd_dump)
    a = p.parse_args()
    a.func(a)


if __name__ == "__main__":
    main()
