#!/usr/bin/env bash
# First-run profile picker. Persists choice to ~/.config/machine-setup/machine.toml
# so subsequent runs are non-interactive.
#
# Caller must have sourced lib/common.sh and set MACHINE_SETUP_DIR.

MACHINE_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/machine-setup"
MACHINE_CONFIG_FILE="$MACHINE_CONFIG_DIR/machine.toml"

# Pick a profile interactively. Sets PROFILE in the caller.
#
# Order of resolution:
#   1. $MACHINE_SETUP_PROFILE env var (override for scripted runs / CI)
#   2. ~/.config/machine-setup/machine.toml `profile = "..."`
#   3. Interactive prompt (whiptail or numeric select)
#
# After interactive selection, the choice is persisted to (2).
ui_pick_profile() {
  if [ -n "${MACHINE_SETUP_PROFILE:-}" ]; then
    PROFILE="$MACHINE_SETUP_PROFILE"
    log "Using profile from MACHINE_SETUP_PROFILE: $PROFILE"
    return 0
  fi

  if [ -f "$MACHINE_CONFIG_FILE" ]; then
    local saved
    saved=$(python3 -c "
import sys
try:
    import tomllib
except ImportError:
    import tomli as tomllib
try:
    with open('$MACHINE_CONFIG_FILE', 'rb') as f:
        print(tomllib.load(f).get('profile', ''))
except Exception:
    pass
")
    if [ -n "$saved" ]; then
      PROFILE="$saved"
      log "Using saved profile: $PROFILE  ($MACHINE_CONFIG_FILE)"
      return 0
    fi
  fi

  _ui_prompt_profile || die "No profile selected"
  _ui_save_profile "$PROFILE"
  log "Saved selection to $MACHINE_CONFIG_FILE"
}

# Re-run the picker even if a saved profile exists.
ui_pick_profile_force() {
  unset MACHINE_SETUP_PROFILE
  rm -f "$MACHINE_CONFIG_FILE"
  ui_pick_profile
}

_ui_save_profile() {
  mkdir -p "$MACHINE_CONFIG_DIR"
  cat > "$MACHINE_CONFIG_FILE" <<EOF
# Auto-generated by machine-setup. Edit to switch profiles, or delete this file
# to be re-prompted on next bootstrap run.
profile = "$1"
EOF
}

_ui_prompt_profile() {
  local profiles_json
  profiles_json=$(python3 "$MACHINE_SETUP_DIR/lib/config.py" list-profiles) \
    || die "Failed to list profiles"

  if [ -z "$profiles_json" ]; then
    die "No profiles found. Add at least one to profiles/ or local/profiles/."
  fi

  # Build parallel arrays: names[i], labels[i] (label = "name — description (source)")
  local names=() labels=()
  while IFS= read -r line; do
    [ -z "$line" ] && continue
    local n d s
    n=$(printf '%s' "$line" | python3 -c "import sys,json; print(json.loads(sys.stdin.read())['name'])")
    d=$(printf '%s' "$line" | python3 -c "import sys,json; print(json.loads(sys.stdin.read()).get('description',''))")
    s=$(printf '%s' "$line" | python3 -c "import sys,json; print(json.loads(sys.stdin.read())['source'])")
    names+=("$n")
    if [ -n "$d" ]; then
      labels+=("$n — $d  [$s]")
    else
      labels+=("$n  [$s]")
    fi
  done <<< "$profiles_json"

  if command -v whiptail >/dev/null 2>&1 && [ -t 0 ]; then
    _ui_whiptail_select names labels
  else
    _ui_select_fallback names labels
  fi
}

_ui_whiptail_select() {
  local -n _names=$1 _labels=$2
  local args=()
  for i in "${!_names[@]}"; do
    args+=("${_names[$i]}" "${_labels[$i]}")
  done
  PROFILE=$(whiptail \
    --title "machine-setup" \
    --menu "Pick a profile for this machine:" \
    20 78 10 \
    "${args[@]}" \
    3>&1 1>&2 2>&3) || return 1
}

_ui_select_fallback() {
  local -n _names=$1 _labels=$2
  echo ""
  echo "Pick a profile for this machine:"
  echo ""
  local i=1
  for label in "${_labels[@]}"; do
    printf "  %d) %s\n" "$i" "$label"
    i=$((i + 1))
  done
  echo ""
  while :; do
    read -r -p "Enter number (1-${#_names[@]}): " choice
    if [[ "$choice" =~ ^[0-9]+$ ]] && [ "$choice" -ge 1 ] && [ "$choice" -le "${#_names[@]}" ]; then
      PROFILE="${_names[$((choice - 1))]}"
      return 0
    fi
    echo "Invalid choice."
  done
}
