#!/usr/bin/env bash
# Per-session helper:  bw-unlock  →  unlocks vault, loads every SSH key from
# every identity in the active profile.
#
# We read the live PLAN_JSON to figure out which BW items to load. The list
# of items is baked into ~/.local/bin/bw-ssh-add at install time so the
# script doesn't need to re-resolve the profile at runtime.

ensure_path

# Build the list of BW SSH item names from the plan
_items=$(printf '%s' "$PLAN_JSON" | python3 -c "
import sys, json
data = json.load(sys.stdin)
items = [i.get('bw_ssh_item','') for i in data.get('identities', []) if i.get('bw_ssh_item')]
for it in items:
    # Single-quote each item for safe inclusion in the bash array literal
    print(\"'\" + it.replace(\"'\", \"'\\\\''\") + \"'\")
" | tr '\n' ' ')

cat > "$HOME/.local/bin/bw-ssh-add" <<EOF
#!/usr/bin/env bash
# Auto-generated by machine-setup. Loads each SSH key into ssh-agent.
# Private keys live only in BW + agent memory — never on disk.
set -euo pipefail

[ -n "\${BW_SESSION:-}" ] || { echo "BW_SESSION not set" >&2; exit 1; }

# Detect that the agent is reachable; fail fast if not (the wrapper function
# in shell rc files starts the agent in the parent shell — see below).
_rc=0; ssh-add -l >/dev/null 2>&1 || _rc=\$?
if [ "\${_rc:-0}" -eq 2 ]; then
  echo "ssh-agent not reachable. Run via the bw-unlock shell function." >&2
  exit 1
fi

_load_bw_key() {
  local item="\$1" priv
  priv=\$(bw list items --search "\$item" 2>/dev/null | python3 -c "
import sys, json
items = json.load(sys.stdin)
match = next((i for i in items if i.get('name') == sys.argv[1]), None)
if match is None: sys.exit(2)
priv = next((f['value'] for f in (match.get('fields') or []) if f.get('name') == 'private_key'), None)
if priv is None: sys.exit(3)
sys.stdout.write(priv)
" "\$item" 2>/dev/null) || { echo "Skipped (not found): \$item"; return; }
  printf '%s\n' "\$priv" | ssh-add - 2>/dev/null && echo "Loaded: \$item" || echo "ssh-add failed for: \$item"
}

for item in $_items; do _load_bw_key "\$item"; done

echo "ssh-agent has \$(ssh-add -l | wc -l) key(s)."
EOF
chmod +x "$HOME/.local/bin/bw-ssh-add"
log "Wrote ~/.local/bin/bw-ssh-add"

# Shell rc snippet: bw-unlock function. The agent MUST be started in the
# parent shell, not in bw-ssh-add (a child process), so SSH_AUTH_SOCK
# survives in the user's interactive shell.
_snippet='
# machine-setup: unlock Bitwarden vault and load every configured SSH key.
# Only spawn a new ssh-agent if the existing socket is unreachable (rc=2);
# rc=1 means "no identities yet" — loading into that agent (typically the
# systemd one at /run/user/$UID/ssh-agent.socket) keeps keys available in
# every shell of the user session until logout / agent restart.
bw-unlock() {
  ssh-add -l >/dev/null 2>&1; local _rc=$?
  if [ -z "${SSH_AUTH_SOCK:-}" ] || [ "$_rc" -eq 2 ]; then
    eval "$(ssh-agent -s)" >/dev/null
  fi
  export BW_SESSION="$(bw unlock --raw)"
  bw-ssh-add
}
'
for rc in "$HOME/.bashrc" "$HOME/.zshrc"; do
  [ -f "$rc" ] || continue
  if grep -q '# machine-setup: unlock Bitwarden' "$rc"; then
    # Replace any prior block (older versions started the agent in the child)
    python3 - "$rc" <<'PY'
import re, sys, pathlib
p = pathlib.Path(sys.argv[1])
text = p.read_text()
new = re.sub(r"\n*# machine-setup: unlock Bitwarden.*?\nbw-unlock\(\) \{.*?\n\}\n", "\n", text, flags=re.S)
p.write_text(new)
PY
  fi
  printf '%s\n' "$_snippet" >> "$rc"
done
log "Installed bw-unlock function in shell rc files"
